// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlcgen

import (
	"context"
	"encoding/json"
)

const appendEvent = `-- name: AppendEvent :one
INSERT INTO events (run_id, seq, type, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, run_id, seq, type, payload, created_at
`

type AppendEventParams struct {
	RunID   string          `json:"run_id"`
	Seq     int32           `json:"seq"`
	Type    string          `json:"type"`
	Payload json.RawMessage `json:"payload"`
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, appendEvent,
		arg.RunID,
		arg.Seq,
		arg.Type,
		arg.Payload,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Seq,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getLastSeq = `-- name: GetLastSeq :one
SELECT COALESCE(MAX(seq), 0)::int AS last_seq
FROM events
WHERE run_id = $1
`

func (q *Queries) GetLastSeq(ctx context.Context, runID string) (int32, error) {
	row := q.db.QueryRow(ctx, getLastSeq, runID)
	var last_seq int32
	err := row.Scan(&last_seq)
	return last_seq, err
}

const listEventsAfter = `-- name: ListEventsAfter :many
SELECT id, run_id, seq, type, payload, created_at FROM events
WHERE run_id = $1 AND id > $2
ORDER BY id ASC
`

type ListEventsAfterParams struct {
	RunID string `json:"run_id"`
	ID    int64  `json:"id"`
}

func (q *Queries) ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsAfter, arg.RunID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Seq,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByRun = `-- name: ListEventsByRun :many
SELECT id, run_id, seq, type, payload, created_at FROM events
WHERE run_id = $1
ORDER BY seq ASC
`

func (q *Queries) ListEventsByRun(ctx context.Context, runID string) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Seq,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
