// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID        int64              `json:"id"`
	RunID     string             `json:"run_id"`
	Seq       int32              `json:"seq"`
	Type      string             `json:"type"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Run struct {
	ID        string             `json:"id"`
	Goal      string             `json:"goal"`
	Status    string             `json:"status"`
	Error     *string            `json:"error"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
