// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package sqlcgen

import (
	"context"
)

const createRun = `-- name: CreateRun :one
INSERT INTO runs (id, goal, status)
VALUES ($1, $2, 'pending')
RETURNING id, goal, status, error, created_at, updated_at
`

type CreateRunParams struct {
	ID   string `json:"id"`
	Goal string `json:"goal"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun, arg.ID, arg.Goal)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Goal,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, goal, status, error, created_at, updated_at FROM runs WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id string) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Goal,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunStatus = `-- name: GetRunStatus :one
SELECT status FROM runs WHERE id = $1
`

func (q *Queries) GetRunStatus(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getRunStatus, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const listRuns = `-- name: ListRuns :many
SELECT id, goal, status, error, created_at, updated_at FROM runs ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListRuns(ctx context.Context, limit int32) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Goal,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByStatus = `-- name: ListRunsByStatus :many
SELECT id, goal, status, error, created_at, updated_at FROM runs WHERE status = $1 ORDER BY created_at ASC
`

func (q *Queries) ListRunsByStatus(ctx context.Context, status string) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRunsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Goal,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunStatus = `-- name: UpdateRunStatus :exec
UPDATE runs
SET status = $2, error = $3, updated_at = now()
WHERE id = $1
`

type UpdateRunStatusParams struct {
	ID     string  `json:"id"`
	Status string  `json:"status"`
	Error  *string `json:"error"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error {
	_, err := q.db.Exec(ctx, updateRunStatus, arg.ID, arg.Status, arg.Error)
	return err
}
